version: '3.4'

services:
  golang:
    image: golang:1.22
    volumes:
      - type: bind
        source: .
        target: /opt/app
    working_dir: /opt/app
    environment:
      - GOARCH
      - GOOS
